baseURL = "https://michalbock.com/"
languageCode = "en-us"
title = "michalbock.com"
theme = "coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Michal Bock"
    info = "Backend Developer"
    description = "Personal website of Michal Bock"
    keywords = "blog,developer,personal"
    avatarurl = "images/michal.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    # custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-3x"
    weight = 1
    url = "https://github.com/SpeedyCoder/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-3x"
    weight = 2
    url = "https://linkedin.com/in/michalbock/"
[[params.social]]
    name = "Meduim"
    icon = "fab fa-medium-m fa-3x"
    weight = 3
    url = "https://medium.com/@michal.bock"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"