version: '3'
services:
  site:
    image: quay.io/speedycoder/michalbock.com:latest
    restart: always
    network_mode: host
    volumes:
      - certs:/certs
      - data:/data
  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  certs: {}
  data: {}
