version: '3'
services:
  site:
    image: quay.io/speedycoder/michalbock.com:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/opt/certs:/certs
      - /root/opt/data:/data
  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600
