version: '3'
services:
  site:
    image: quay.io/speedycoder/michalbock.com:latest
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
